server:
  port: 80

spring:
  datasource:
    #   数据源基本配置
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hajimiemasidie?serverTimezone=GMT%2B8&characterEncoding=UTF-8
  redis:
    host: localhost
    password:
    database: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis-config.xml

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper

logging:
  level:
    cn.lsz.gongzhonghao.hajimiemasidie: debug
  file:
    path: src\main\resources\log

wx:
  token: 1
  app-id: 1
  app-secrect: 1
  wechat-id: 1

