server:
  port: 80

spring:
  datasource:
    #   数据源基本配置
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
  redis:
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    database: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    cn.lsz.gongzhonghao.hajimiemasidie: debug

wx:
  token:
  app-id:
  app-secrect:
  wechat-id:

mybatis:
  configuration:
    map-underscore-to-camel-case: true