server:
  port: 80

spring:
  datasource:
    #   数据源基本配置
    username: hajimiemasidie
    password: hajimiemasidie
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.28:3306/hajimiemasidie?serverTimezone=GMT%2B8&characterEncoding=UTF-8
  redis:
    host: 192.168.10.28
    password:
    database: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


logging:
  level:
    cn.lsz.gongzhonghao.hajimiemasidie: debug
  file:
    path: src\main\resources\log

wx:
  token: 1
  app-id: 1
  app-secrect: 1
  wechat-id: 1

mybatis:
  configuration:
    map-underscore-to-camel-case: true
